# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/lvyuf/Desktop/NSCSCC_TRYOUT/func_test/soc/soc_lite_func_test/rtl/xilinx_ip/data_ram/data_ram.xci
# IP: The module: 'data_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lvyuf/Desktop/NSCSCC_TRYOUT/func_test/soc/soc_lite_func_test/rtl/xilinx_ip/data_ram/data_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/lvyuf/Desktop/NSCSCC_TRYOUT/func_test/soc/soc_lite_func_test/rtl/xilinx_ip/data_ram/data_ram.xci
# IP: The module: 'data_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lvyuf/Desktop/NSCSCC_TRYOUT/func_test/soc/soc_lite_func_test/rtl/xilinx_ip/data_ram/data_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
