# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/lvyuf/Desktop/result/func_test/soc/soc_lite_func_test_delay_ram/rtl/xilinx_ip/inst_ram/inst_ram.xci
# IP: The module: 'inst_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lvyuf/Desktop/result/func_test/soc/soc_lite_func_test_delay_ram/rtl/xilinx_ip/inst_ram/inst_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'inst_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: C:/Users/lvyuf/Desktop/result/func_test/soc/soc_lite_func_test_delay_ram/rtl/xilinx_ip/inst_ram/inst_ram.xci
# IP: The module: 'inst_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lvyuf/Desktop/result/func_test/soc/soc_lite_func_test_delay_ram/rtl/xilinx_ip/inst_ram/inst_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'inst_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
