# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/CQU-LS/Desktop/func_test/soc/soc_lite_func_test/run_vivado/soc_lite.xdc

# IP: C:/Users/CQU-LS/Desktop/func_test/soc/soc_lite_func_test/rtl/xilinx_ip/ahblite_axi_bridge_0/ahblite_axi_bridge_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ahblite_axi_bridge_0 || ORIG_REF_NAME==ahblite_axi_bridge_0}]

# IP: C:/Users/CQU-LS/Desktop/func_test/soc/soc_lite_func_test/rtl/xilinx_ip/clk_pll/clk_pll.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_pll || ORIG_REF_NAME==clk_pll}]
