# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/CQU-LS/Desktop/func_test/memory_game/soc_lite/vivado_xpr/soc_lite.xdc

# IP: C:/Users/CQU-LS/Desktop/func_test/memory_game/soc_lite/vivado_xpr/memory_game/xilinx_ip/data_ram/data_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==data_ram || ORIG_REF_NAME==data_ram}]

# IP: C:/Users/CQU-LS/Desktop/func_test/memory_game/soc_lite/vivado_xpr/memory_game/xilinx_ip/inst_ram/inst_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==inst_ram || ORIG_REF_NAME==inst_ram}]

# IP: C:/Users/CQU-LS/Desktop/func_test/memory_game/soc_lite/vivado_xpr/memory_game/xilinx_ip/ahblite_axi_bridge_0/ahblite_axi_bridge_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ahblite_axi_bridge_0 || ORIG_REF_NAME==ahblite_axi_bridge_0}]

# IP: C:/Users/CQU-LS/Desktop/func_test/memory_game/soc_lite/vivado_xpr/memory_game/xilinx_ip/clk_pll/clk_pll.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_pll || ORIG_REF_NAME==clk_pll}]
