# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/lvyuf/Desktop/result/func_test/soc/soc_lite_func_test_delay_ram/run_vivado/soc_lite.xdc

# IP: C:/Users/lvyuf/Desktop/result/func_test/soc/soc_lite_func_test_delay_ram/rtl/xilinx_ip/data_ram/data_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==data_ram || ORIG_REF_NAME==data_ram}]

# IP: C:/Users/lvyuf/Desktop/result/func_test/soc/soc_lite_func_test_delay_ram/rtl/xilinx_ip/axi_crossbar_0/axi_crossbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axi_crossbar_0 || ORIG_REF_NAME==axi_crossbar_0}]

# IP: C:/Users/lvyuf/Desktop/result/func_test/soc/soc_lite_func_test_delay_ram/rtl/xilinx_ip/ahblite_axi_bridge_0/ahblite_axi_bridge_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ahblite_axi_bridge_0 || ORIG_REF_NAME==ahblite_axi_bridge_0}]

# IP: C:/Users/lvyuf/Desktop/result/func_test/soc/soc_lite_func_test_delay_ram/rtl/xilinx_ip/clk_pll/clk_pll.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_pll || ORIG_REF_NAME==clk_pll}]
